# first step parameters
## size of the context window
window_size: 20
## maximum vocab_size
vocab_size: 5000
## the number of paritions to divide cooccurence matrix in 
num_partitions: 10
## chunk size of h5py.Dataset
chunk_size: 1000000

# when used in first step, specify the output directory of cooccurrence entries
# when used in second step, specify where to read cooccurrence entries from
cooccurrence_dir: ../processed_data/utrs/cooccurence

# second step parameters
## output path for the trained word vectors 
output_filepath: ../model/utrs/gloveModel
## pytorch training parameters
batch_size: 128
num_epochs: 100
device: cuda
learning_rate: 0.1
## glove paremeters
embedding_size: 30
x_max: 100
alpha: 0.75
